# Generated by Django 5.2.7 on 2025-10-24 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("biocontrol_agent_name", models.CharField(max_length=255)),
                ("biocontrol_agent_strain", models.CharField(max_length=255)),
                (
                    "accession_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("biofertilizer", "Biofertilizer"),
                            ("biopesticide", "Biopesticide"),
                            ("biostimulant", "Biostimulant"),
                            ("biocontrol", "Biocontrol"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "formulation",
                    models.CharField(
                        choices=[
                            ("aqueous_suspension", "Aqueous Suspension"),
                            ("wettable_powder", "Wettable Powder"),
                            ("emulsion", "Emulsion"),
                            ("suspension", "Suspension"),
                        ],
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                (
                    "registration_status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("pending", "Pending"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "registered_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("registration_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="website.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "country")},
            },
        ),
    ]
