# Generated by Django 5.2.7 on 2025-10-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_product_productregistration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productregistration",
            name="registered_by",
        ),
    ]
