# Generated by Django 5.2.7 on 2025-10-24 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_remove_productregistration_registered_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="product_docs/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="website.product",
                    ),
                ),
            ],
        ),
    ]
