# Generated by Django 5.2.7 on 2025-10-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_productdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cfu",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
