# Generated by Django 5.2.7 on 2025-10-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_product_cfu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdocument",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="product_docs/"),
        ),
    ]
