# Generated by Django 5.2.7 on 2025-10-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_alter_productdocument_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="institution_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
