# Generated by Django 5.2.7 on 2025-10-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_membership_membershipdocument_membershippayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membership",
            name="district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
