# Generated by Django 5.2.7 on 2025-10-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_membership_address_membership_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershippayment",
            name="payment_proof",
            field=models.FileField(blank=True, null=True, upload_to="payment_proofs/"),
        ),
    ]
