# Generated by Django 5.2.7 on 2025-10-25 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0013_membershippayment_verification_remarks_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quotation",
            name="email",
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="responsible_person",
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[("INR", "INR"), ("USD", "USD")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="quoted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="quoted_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
