# Generated by Django 5.2.7 on 2025-10-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0014_remove_quotation_email_remove_quotation_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotationguidelinefile",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="quotation_guidelines/"
            ),
        ),
    ]
